#################################################
##############ElasticSearch 접속정보##############
#################################################
elasticsearch:
  - id: "data"
    use: true
    uri: ["127.0.0.1:9200"]
    workers: 0
    io_thread: 3
    connection_timeout: 5000
    read_timeout: 600000
    credential: ""